export const ASSET_CATEGORIES = [
  "포스터",
  "전경·현장 사진",
  "서문 / 기획 의도",
  "작가·아티스트 소개",
  "보도자료 초안",
  "기타 홍보 기초자료",
];

// storage-safe folder names, same order as ASSET_CATEGORIES
export const ASSET_CATEGORY_SLUGS = ["poster", "photos", "intro", "artist", "press", "misc"];

export const concerts = [
  {
    id: "rec-014",
    code: "REC.014",
    title: "쇼팽 노크턴의 밤",
    sub: "피아노 독주회",
    date: "2026.09.12",
    venue: "헤레디움 채플홀",
    status: "예정",
    blurb: "야상곡 전곡을 저녁 예배당의 잔향 속에서 듣는 프로그램.",
    description:
      "쇼팽의 야상곡 21곡을 연대순으로 배치해 초기작의 서정성부터 후기작의 내적 갈등까지 한 번에 조망하는 독주회입니다. 채플홀 특유의 잔향을 살려 마이크 없이 진행하며, 인터미션 없이 90분간 이어집니다.",
    checklist: [
      { label: "포스터 최종 확정", done: true },
      { label: "SNS 예고 게시물 3종", done: true },
      { label: "보도자료 배포", done: false },
      { label: "리허설 일정 확정", done: false },
      { label: "좌석 배치도 인쇄", done: false },
    ],
    links: [
      { label: "티켓 예매 페이지", href: "#" },
      { label: "SNS 예고 게시물", href: "#" },
      { label: "카드뉴스 초안", href: "#" },
    ],
  },
  {
    id: "rec-013",
    code: "REC.013",
    title: "여름밤의 현악 4중주",
    sub: "실내악 시리즈",
    date: "2026.08.22",
    venue: "헤레디움 마당",
    status: "예정",
    blurb: "드보르작과 브람스를 중심으로 구성한 야외 상설 공연.",
    description:
      "헤레디움 마당에서 진행되는 여름 상설 실내악 시리즈. 드보르작 현악 4중주 12번 '아메리카'와 브람스 2번을 연주하며, 우천 시 채플홀로 장소를 옮깁니다.",
    checklist: [
      { label: "포스터 최종 확정", done: true },
      { label: "SNS 예고 게시물 3종", done: false },
      { label: "우천 대비 채플홀 예약", done: true },
      { label: "음향 장비 점검", done: false },
    ],
    links: [
      { label: "티켓 예매 페이지", href: "#" },
      { label: "SNS 예고 게시물", href: "#" },
    ],
  },
  {
    id: "rec-012",
    code: "REC.012",
    title: "바로크 트럼펫 갈라",
    sub: "금관 앙상블",
    date: "2026.07.30",
    venue: "헤레디움 채플홀",
    status: "예매중",
    blurb: "비발디·헨델의 트럼펫 협주 레퍼토리.",
    description: "비발디와 헨델의 트럼펫 협주곡을 중심으로 구성된 금관 앙상블 공연입니다.",
    checklist: [
      { label: "포스터 최종 확정", done: true },
      { label: "SNS 예고 게시물 3종", done: true },
      { label: "보도자료 배포", done: true },
    ],
    links: [{ label: "티켓 예매 페이지", href: "#" }],
  },
  {
    id: "rec-011",
    code: "REC.011",
    title: "첼로와 목소리",
    sub: "크로스오버",
    date: "2026.06.14",
    venue: "헤레디움 채플홀",
    status: "종료",
    blurb: "국악 성악가와 첼리스트의 협연 무대.",
    description: "국악 성악가와 첼리스트가 함께한 크로스오버 공연으로, 전통 성악과 서양 현악기의 대화를 시도했습니다.",
    checklist: [
      { label: "포스터 최종 확정", done: true },
      { label: "SNS 예고 게시물 3종", done: true },
      { label: "보도자료 배포", done: true },
      { label: "종료 후 결과 리포트 작성", done: true },
    ],
    links: [{ label: "공연 결과 리포트", href: "#" }],
  },
  {
    id: "rec-010",
    code: "REC.010",
    title: "리스트, 초절기교",
    sub: "피아노 독주회",
    date: "2026.05.03",
    venue: "헤레디움 채플홀",
    status: "종료",
    blurb: "초절기교 연습곡 12번 전곡 연주.",
    description: "리스트의 초절기교 연습곡 12곡을 전곡 연주한 독주회입니다.",
    checklist: [
      { label: "포스터 최종 확정", done: true },
      { label: "SNS 예고 게시물 3종", done: true },
      { label: "종료 후 결과 리포트 작성", done: true },
    ],
    links: [{ label: "공연 결과 리포트", href: "#" }],
  },
];

export const exhibitions = [
  {
    id: "exh-037",
    code: "EXH.037",
    title: "시오타 치하루",
    sub: "기억의 빛 속으",
    date: "2026.08 – 2026.11",
    venue: "헤레디움 전관",
    status: "얼리버드",
    blurb: "실과 빛으로 엮은 기억의 지형을 따라가는 대규모 설치.",
    description:
      "시오타 치하루의 대표작인 실 설치 작업을 중심으로 기억과 부재를 다루는 대규모 개인전입니다. 전관을 사용하는 첫 전시로, 2관 전체가 하나의 설치 작품으로 채워집니다.",
    checklist: [
      { label: "얼리버드 티켓 오픈", done: true },
      { label: "포스터/현수막 확정", done: true },
      { label: "특별 강연 2회 일정 확정", done: false },
      { label: "보도자료 배포", done: false },
      { label: "도록 인쇄", done: false },
    ],
    links: [
      { label: "얼리버드 티켓 페이지", href: "https://heredium.art/community/notice/37" },
      { label: "카드뉴스 초안", href: "#" },
    ],
  },
  {
    id: "exh-036",
    code: "EXH.036",
    title: "이봉 랑베르",
    sub: "예술가의 곁에서",
    date: "2026.05 – 2026.07",
    venue: "헤레디움 2관",
    status: "종료",
    blurb: "낸 골딘 작품을 포함한 사진 아카이브 전시.",
    description:
      "프랑스 사진가 이봉 랑베르가 예술가들의 곁에서 포착한 사진 아카이브 전시로, 낸 골딘의 작품이 포함되어 화제가 되었습니다.",
    checklist: [
      { label: "포스터/현수막 확정", done: true },
      { label: "보도자료 배포", done: true },
      { label: "종료 후 결과 리포트 작성", done: true },
    ],
    links: [
      { label: "관람 안내 공지", href: "https://heredium.art/community/notice/34" },
      { label: "전시 결과 리포트", href: "#" },
    ],
  },
  {
    id: "exh-035",
    code: "EXH.035",
    title: "김환기 이후",
    sub: "점, 선, 면",
    date: "2026.02 – 2026.04",
    venue: "헤레디움 1관",
    status: "종료",
    blurb: "추상 회화의 계보를 잇는 국내 작가 4인전.",
    description: "김환기의 조형 언어를 계승하는 국내 추상화가 4인의 그룹전입니다.",
    checklist: [
      { label: "포스터/현수막 확정", done: true },
      { label: "종료 후 결과 리포트 작성", done: true },
    ],
    links: [{ label: "전시 결과 리포트", href: "#" }],
  },
  {
    id: "exh-034",
    code: "EXH.034",
    title: "빛과 벽돌",
    sub: "건축과 미술 사이",
    date: "2025.11 – 2026.01",
    venue: "헤레디움 전관",
    status: "종료",
    blurb: "헤레디움 건축물 자체를 소재로 한 커미션 워크.",
    description: "헤레디움 건축 공간 자체를 소재로 삼은 커미션 신작 위주의 전시였습니다.",
    checklist: [
      { label: "포스터/현수막 확정", done: true },
      { label: "종료 후 결과 리포트 작성", done: true },
    ],
    links: [{ label: "전시 결과 리포트", href: "#" }],
  },
];
